Fix test workflow

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -12,6 +12,12 @@ on:
     paths-ignore:
       - '**.md'
 
+env:
+  BUILD_TAG: test
+  CONTAINER_NAME: nextcloud
+  RUNNING_TIMEOUT: 120
+  RUNNING_LOG_CHECK: ready to handle connections
+
 jobs:
   test:
     runs-on: ubuntu-latest
@@ -27,30 +33,22 @@ jobs:
         name: Checkout
         uses: actions/checkout@v3
       -
-        name: Prepare
-        id: prep
-        run: |
-          echo ::set-output name=build_tag::test
-          echo ::set-output name=container_name::nextcloud
-          echo ::set-output name=running_timeout::120
-          echo ::set-output name=running_log_check::ready to handle connections
-      -
         name: Docker Build
         uses: docker/bake-action@v2
         with:
           targets: image-local
         env:
-          DEFAULT_TAG: ${{ steps.prep.outputs.build_tag }}
+          DEFAULT_TAG: ${{ env.BUILD_TAG }}
           DOCKERFILE: ${{ matrix.docker_file }}
       -
         name: Create network
         run: |
-          docker network create -d bridge ${{ steps.prep.outputs.container_name }}
+          docker network create -d bridge ${{ env.CONTAINER_NAME }}
       -
         name: Start MariaDB container
         run: |
           docker run -d --name mariadb --hostname mariadb \
-            --network ${{ steps.prep.outputs.container_name }} \
+            --network ${{ env.CONTAINER_NAME }} \
             -e "MYSQL_ALLOW_EMPTY_PASSWORD=yes" \
             -e "MYSQL_DATABASE=nextcloud" \
             -e "MYSQL_USER=nextcloud" \
@@ -59,38 +57,38 @@ jobs:
       -
         name: Start container
         run: |
-          docker run -d --name ${{ steps.prep.outputs.container_name }} \
+          docker run -d --name ${{ env.CONTAINER_NAME }} \
             --link mariadb \
-            --network ${{ steps.prep.outputs.container_name }} \
+            --network ${{ env.CONTAINER_NAME }} \
             -e "DB_HOST=mariadb" \
             -e "DB_NAME=nextcloud" \
             -e "DB_USER=nextcloud" \
             -e "DB_PASSWORD=asupersecretpassword" \
-            ${{ steps.prep.outputs.build_tag }}
+            ${{ env.BUILD_TAG }}
       -
         name: Test run
         run: |
-          TIMEOUT=$((SECONDS + ${{ steps.prep.outputs.running_timeout }}))
+          TIMEOUT=$((SECONDS + ${{ env.RUNNING_TIMEOUT }}))
           while read LOGLINE; do
             echo ${LOGLINE}
-            if [[ ${LOGLINE} == *"${{ steps.prep.outputs.running_log_check }}"* ]]; then
-              echo "🎉 Container up!"
+            if [[ ${LOGLINE} == *"${{ env.RUNNING_LOG_CHECK }}"* ]]; then
+              echo "Container up!"
               break
             fi
             if [[ $SECONDS -gt ${TIMEOUT} ]]; then
-              >&2 echo "❌ Failed to run ${{ steps.prep.outputs.container_name }} container"
+              >&2 echo "Failed to run ${{ env.CONTAINER_NAME }} container"
               exit 1
             fi
-          done < <(docker logs -f ${{ steps.prep.outputs.container_name }} 2>&1)
+          done < <(docker logs -f ${{ env.CONTAINER_NAME }} 2>&1)
 
-          CONTAINER_STATUS=$(docker container inspect --format "{{.State.Status}}" ${{ steps.prep.outputs.container_name }})
+          CONTAINER_STATUS=$(docker container inspect --format "{{.State.Status}}" ${{ env.CONTAINER_NAME }})
           if [[ ${CONTAINER_STATUS} != "running" ]]; then
-            >&2 echo "❌ Container ${{ steps.prep.outputs.container_name }} returned status '$CONTAINER_STATUS'"
+            >&2 echo "Container ${{ env.CONTAINER_NAME }} returned status '$CONTAINER_STATUS'"
             exit 1
           fi
       -
         name: Container logs
         if: always()
         run: |
-          docker logs ${{ steps.prep.outputs.container_name }}
-          docker rm -f ${{ steps.prep.outputs.container_name }} > /dev/null 2>&1 || true
+          docker logs ${{ env.CONTAINER_NAME }}
+          docker rm -f ${{ env.CONTAINER_NAME }} > /dev/null 2>&1 || true
