Switch to Docker actions

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -28,7 +28,7 @@ jobs:
         uses: actions/checkout@v2.3.2
       -
         name: Prepare
-        id: prepare
+        id: prep
         run: |
           echo ::set-output name=build_tag::test
           echo ::set-output name=container_name::nextcloud
@@ -37,16 +37,16 @@ jobs:
       -
         name: Docker Build
         run: |
-          docker build --tag ${{ steps.prepare.outputs.build_tag }} --file ${{ matrix.docker_file }} .
+          docker build --tag ${{ steps.prep.outputs.build_tag }} --file ${{ matrix.docker_file }} .
       -
         name: Create network
         run: |
-          docker network create -d bridge ${{ steps.prepare.outputs.container_name }}
+          docker network create -d bridge ${{ steps.prep.outputs.container_name }}
       -
         name: Start MariaDB container
         run: |
           docker run -d --name mariadb --hostname mariadb \
-            --network ${{ steps.prepare.outputs.container_name }} \
+            --network ${{ steps.prep.outputs.container_name }} \
             -e "MYSQL_ALLOW_EMPTY_PASSWORD=yes" \
             -e "MYSQL_DATABASE=nextcloud" \
             -e "MYSQL_USER=nextcloud" \
@@ -55,35 +55,35 @@ jobs:
       -
         name: Start container
         run: |
-          docker run -d --name ${{ steps.prepare.outputs.container_name }} \
+          docker run -d --name ${{ steps.prep.outputs.container_name }} \
             --link mariadb \
-            --network ${{ steps.prepare.outputs.container_name }} \
+            --network ${{ steps.prep.outputs.container_name }} \
             -e "DB_HOST=mariadb" \
             -e "DB_NAME=nextcloud" \
             -e "DB_USER=nextcloud" \
             -e "DB_PASSWORD=asupersecretpassword" \
-            ${{ steps.prepare.outputs.build_tag }}
+            ${{ steps.prep.outputs.build_tag }}
       -
         name: Test run
         run: |
-          TIMEOUT=$((SECONDS + ${{ steps.prepare.outputs.running_timeout }}))
+          TIMEOUT=$((SECONDS + ${{ steps.prep.outputs.running_timeout }}))
           while read LOGLINE; do
             echo ${LOGLINE}
-            if [[ ${LOGLINE} == *"${{ steps.prepare.outputs.running_log_check }}"* ]]; then
+            if [[ ${LOGLINE} == *"${{ steps.prep.outputs.running_log_check }}"* ]]; then
               echo "🎉 Container up!"
               break
             fi
             if [[ $SECONDS -gt ${TIMEOUT} ]]; then
-              >&2 echo "❌ Failed to run ${{ steps.prepare.outputs.container_name }} container"
-              docker rm -f ${{ steps.prepare.outputs.container_name }} > /dev/null 2>&1 || true
+              >&2 echo "❌ Failed to run ${{ steps.prep.outputs.container_name }} container"
+              docker rm -f ${{ steps.prep.outputs.container_name }} > /dev/null 2>&1 || true
               exit 1
             fi
-          done < <(docker logs -f ${{ steps.prepare.outputs.container_name }} 2>&1)
+          done < <(docker logs -f ${{ steps.prep.outputs.container_name }} 2>&1)
 
-          CONTAINER_STATUS=$(docker container inspect --format "{{.State.Status}}" ${{ steps.prepare.outputs.container_name }})
+          CONTAINER_STATUS=$(docker container inspect --format "{{.State.Status}}" ${{ steps.prep.outputs.container_name }})
           if [[ ${CONTAINER_STATUS} != "running" ]]; then
-            >&2 echo "❌ Container ${{ steps.prepare.outputs.container_name }} returned status '$CONTAINER_STATUS'"
-            docker rm -f ${{ steps.prepare.outputs.container_name }} > /dev/null 2>&1 || true
+            >&2 echo "❌ Container ${{ steps.prep.outputs.container_name }} returned status '$CONTAINER_STATUS'"
+            docker rm -f ${{ steps.prep.outputs.container_name }} > /dev/null 2>&1 || true
             exit 1
           fi
-          docker rm -f ${{ steps.prepare.outputs.container_name }} > /dev/null 2>&1 || true
+          docker rm -f ${{ steps.prep.outputs.container_name }} > /dev/null 2>&1 || true
